apiVersion: v1
kind: Service
metadata:
  name: home-coach
  labels:
    helm.sh/chart: home-coach
    app.kubernetes.io/name: home-coach
    app.kubernetes.io/instance: home-coach
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: home-coach
    app.kubernetes.io/instance: home-coach
